apiVersion: v1
kind: Service
metadata:
  name: finacplus-service
  labels:
    app: finacplus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: finacplus
    color: {{ .Values.liveColor | quote }}
